# Generated by Django 6.0.2 on 2026-02-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, verbose_name="Nickname"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.CharField(
                blank=True,
                default="default_avatar.png",
                max_length=255,
                null=True,
                verbose_name="Avatar",
            ),
        ),
    ]
