# Generated by Django 6.0.2 on 2026-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_nickname_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="interests_embedding",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Interests Embedding"
            ),
        ),
    ]
