# Generated by Django 6.0.2 on 2026-03-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_interests_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferences_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Travel Context / Wishes"
            ),
        ),
    ]
