# AI / Embeddings
RECOMMENDATION_SIMILARITY_THRESHOLD = 0.6
MAX_RECOMMENDATIONS = 5

# JWT / Cookies
ACCESS_TOKEN_COOKIE_AGE = 3 * 24 * 3600
REFRESH_TOKEN_COOKIE_AGE = 14 * 24 * 3600

# External APIs
EXTERNAL_API_TIMEOUT = 5

# Recommendation defaults
DEFAULT_RECOMMENDATION_CITY = "Paris"
