# Generated by Django 6.0.2 on 2026-03-03 20:59

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("preferences", "0005_alter_preferenceoption_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="City Name"
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        max_length=100, null=True, unique=True, verbose_name="City Name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, null=True, unique=True, verbose_name="City Name"
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                (
                    "country_uk",
                    models.CharField(max_length=100, null=True, verbose_name="Country"),
                ),
                (
                    "country_en",
                    models.CharField(max_length=100, null=True, verbose_name="Country"),
                ),
                (
                    "country_code",
                    models.CharField(max_length=2, verbose_name="Country Code"),
                ),
                (
                    "lat",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "lon",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "name_uk",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address"
                    ),
                ),
                ("lat", models.FloatField(verbose_name="Latitude")),
                ("lon", models.FloatField(verbose_name="Longitude")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_uk",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=384, null=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="preferences.preferencecategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="locations.city",
                        verbose_name="City",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
    ]
