# Generated by Django 6.0.3 on 2026-03-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripplan",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tripplan",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
