# Generated by Django 6.0.3 on 2026-03-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("trips", "0002_alter_tripplan_end_date_alter_tripplan_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="day",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="languagephrase",
            name="language_code",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("uk", "Ukrainian"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_recommendations",
                to="locations.location",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recommendation",
            unique_together={("trip_plan", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="weatherforecast",
            unique_together={("trip_plan", "date")},
        ),
    ]
