# Generated by Django 6.0.3 on 2026-03-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_recommendation_day_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recommendation",
            options={"ordering": ["day"]},
        ),
    ]
