# Generated by Django 6.0.3 on 2026-03-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_alter_recommendation_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languagephrase",
            name="language_code",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("uk", "Ukrainian"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("pl", "Polish"),
                    ("it", "Italian"),
                    ("de", "German"),
                ],
                max_length=10,
            ),
        ),
    ]
