# Generated by Django 6.0.3 on 2026-03-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_alter_languagephrase_language_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weatherforecast",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="weatherforecast",
            name="trip_plan",
        ),
        migrations.DeleteModel(
            name="CurrencyRate",
        ),
        migrations.DeleteModel(
            name="WeatherForecast",
        ),
    ]
