# Generated by Django 6.0.3 on 2026-03-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_alter_weatherforecast_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="languagephrase",
            options={
                "verbose_name": "Language Phrase",
                "verbose_name_plural": "Language Phrases",
            },
        ),
        migrations.AlterModelOptions(
            name="recommendation",
            options={
                "ordering": ["day"],
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
            },
        ),
        migrations.AlterModelOptions(
            name="tripplan",
            options={"verbose_name": "Trip Plan", "verbose_name_plural": "Trip Plans"},
        ),
        migrations.AlterField(
            model_name="languagephrase",
            name="language_code",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("uk", "Ukrainian"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("pl", "Polish"),
                    ("it", "Italian"),
                    ("de", "German"),
                ],
                max_length=10,
                verbose_name="Language",
            ),
        ),
    ]
