# Generated by Django 6.0.2 on 2026-02-16 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0003_alter_preferencecategory_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="preferencecategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Preference Category",
                "verbose_name_plural": "Preference Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="preferenceoption",
            options={"ordering": ["name"]},
        ),
        migrations.AlterUniqueTogether(
            name="preferenceoption",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="userpreference",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="preferenceoption",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="unique_option_per_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="preferenceoption",
            constraint=models.UniqueConstraint(
                fields=("category", "name_uk"),
                name="unique_option_per_category-name_uk",
            ),
        ),
        migrations.AddConstraint(
            model_name="preferenceoption",
            constraint=models.UniqueConstraint(
                fields=("category", "name_en"),
                name="unique_option_per_category-name_en",
            ),
        ),
        migrations.AddConstraint(
            model_name="userpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "preference_option"), name="unique_user_preference"
            ),
        ),
    ]
