# Generated by Django 6.0.2 on 2026-02-17 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0004_alter_preferencecategory_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="preferenceoption",
            options={
                "ordering": ["name"],
                "verbose_name": "Option",
                "verbose_name_plural": "Preference options",
            },
        ),
        migrations.AlterModelOptions(
            name="userpreference",
            options={
                "verbose_name": "User preference",
                "verbose_name_plural": "User preferences",
            },
        ),
        migrations.AlterField(
            model_name="preferenceoption",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="preferences.preferencecategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="preference_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="preferences.preferenceoption",
                verbose_name="Preference option",
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
